### ISSUE TITLE
OmniFormEmailHandler help text

### ISSUE THREAD

**Issue by fatboystring** [omni-digital/omni-forms#9]
The OmniFormEmailHandler class contains a `template` field allowing administrators to define the contents of the email to be sent.  

This handler will be passed an arbitrary cleaned form data dict (depending on the form class that uses it) as the template context.  It would be extremely useful if the available template context variables were made available to administrators in the django admin as help text.

This should be possible using introspection

**Comment by fatboystring** [comment]
#11 Related issue

**Comment by pawelad** [comment]
Okay. I looked through the code to be sure that I understand what happens under the hood. It took me a while - especially since I don't really have experience with a plugins that depends so heavily on Django Admin - buy it's nicely written and I think I understand it well now.

I'll want to go through the issue and my proposed solution, while being extra verbose to make sure that what I seen and deduced is correct.

The task is to dynamically update `help_text` of `OmniFormEmailHandler().template` field, so the current variables available in context are seen.
That could be done either on model or on form level, but I didn't come up with a nice way to dynamically add it on model level. I'm also not sure if that's actually the best place to put it.
The form I itself is currently a `ModelForm`which is dynamically generated  and comes with `modelform_factory` (that is currently used), which takes `help_texts` as an argument. I think that's the best way to do it, following `_get_form_widgets()` convention that's already in use and keeping it mind that that the same solution could be used when regular `Form`s will be introduced in the future.

The only problem that I see, is that `OmniModelFormCreateHandlerView` / `OmniModelFormUpdateHandlerView` is a generic view for all handlers and we want to only update the `template.help_text` if it's `OmniFormEmailHandler`. Currently the only solution I can think of is a hardcoded `if` that checks if the form is `OmniFormEmailHandler`. I wanted to check with you, maybe you have an idea how to do it better?

**Comment by fatboystring** [comment]
Hi Pawel.  Great analysis and you're spot on re: your assessment of the problem.

One thing to bare in mind is that the form handlers that are currently available in the codebase can (and likely will) be added to (either within the core library or by a 3rd party).  As such the model forms you make reference to should ideally remain generic (i.e. no isinstance checks for the type of model being used).

Personally I'd be inclined to set the 'template' fields help text on initialization of the OmniFormEmailHandler model instance and let the model form factory do the rest.  I personally feel it's a cleaner solution and avoids putting edge cases into the forms themselves.

Happy to chat this through more if you like.

**Comment by pawelad** [comment]
Personally I'd be inclined to set the 'template' fields help text on initialization of the OmniFormEmailHandler model instance

**Comment by pawelad** [comment]
A while ago a read a full article about how overriding `__init__` in Django is the wrong way to do it, but I can't find it anywhere. Django [docs](https://docs.djangoproject.com/en/1.9/ref/models/instances/) mention alternatives that always covered all my need, but they won't help in this situation, and overriding `__init__` isn't expplicitly condemned. Only thing I found is [this](http://stackoverflow.com/a/9416417/3023841), but no real argumentes were given and I like the proposed solution even less. So `__init_` it is.

Unfortunately when done that way the variables are only available on handler editing and not creating since we don't know the `OmiForm` until saving, and we can't get it from the view in model `__init__`.

All the changes are available in my fork, feel free to have a look and let me know if you have any suggestions.
Only things left are tests, which I started writing but came up with a question that I can't figure out - are we testing `OmniFormEmailHandler.handle()` with passed `form` with `cleaned_data` or `OmniForm` with linked fields and `OmniFormEmailHandler`. Both?
Currently those are synonymous, but could very easily not be with future changes to the code. It would be great if I could have your input on that.

**Comment by fatboystring** [comment]
Hi Pawel,

Given the context in the stack overflow post you linked to above I'd be inclined to agree that the approach is wrong.  In this context though I do not see any issue with overriding the __init__ method of the model class.  That said, depending on the approach this could incur extra unnecessary hits on the database (i.e. you'd need to select fields from the related form model instance).  There are ways around this (lazy evaluation for example) that could be used to mitigate the issue.  

I see your point about the variables only being available on the handler post creation and to be honest it's not something I had considered.  

Re: your question about testing.  I'm not sure why we would need to write any further tests for the handle method of the handler.  Maybe i'm missing something here but the handle method is called when the model forms save method is invoked.  It doesn't have anything to do with the admin forms or the associated fields help text.
